/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    BracketView: typeof import('./src/components/bracketView/BracketView.vue')['default']
    BtnConfirm: typeof import('./src/components/btnConfirm/btnConfirm.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    KnockoutBracket: typeof import('./src/components/bracketView/KnockoutBracket.vue')['default']
    NToolbar: typeof import('./src/components/nToolbar/nToolbar.vue')['default']
    PhaseStepper: typeof import('./src/components/phaseStepper/phaseStepper.vue')['default']
    PhaseTimeLine: typeof import('./src/components/phaseTimeLine/phaseTimeLine.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableFase: typeof import('./src/components/tableFase/tableFase.vue')['default']
  }
}
